# Import Libraries

In [6]:
import numpy as np

# Cek Versi Numpy

In [2]:
np.__version__

'1.18.1'

## Mendapatkan Informasi Fungsi Numpy

In [4]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

## Matriks menggunakan Numpy

In [152]:
# Python List
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [34]:
print(a+b)

[1, 2, 3, 5, 6, 7, 8]


In [11]:
v = np.array([1, 2, 3])

v

array([1, 2, 3])

In [24]:
m = np.array([[1, 2, 3], [4, 5, 6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [18]:
a = [1,2,3]

In [19]:
type(a)

list

In [27]:
v.shape

(3,)

In [28]:
m.shape

(2, 3)

In [29]:
v.size

3

In [30]:
m.size

6

In [31]:
m.dtype

dtype('int32')

### Penjumlahan Matriks

In [153]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Create Matrix Zeros

In [39]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [45]:
#two dimension

zeros_matrix2 = np.zeros((5,2))
zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [154]:
#3 dimension

zeros_matrix3 = np.zeros((4, 2, 3))
zeros_matrix3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Studi Kasus 1

### Soal 1 Buat matriks dengan 4 baris dan 3 kolom

In [73]:
x = np.array([[1,2,3,4],
               [3,9,3,4],
               [4,0,1,3],
               [1,2,3,4]])
print(x)

[[1 2 3 4]
 [3 9 3 4]
 [4 0 1 3]
 [1 2 3 4]]


### Soal 2 Matriks

In [157]:
x = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
print(x)

[[ 2  7 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


### Soal 3 Matriks 2 dimensi dengan jumlah elemen 10

In [71]:
m = np.array([[1, 2, 3, 4, 5], 
              [1, 2, 3, 5, 6]])

m

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 5, 6]])

In [72]:
m.size

10

### Soal 4 buat matriks 3D 2 baris, 3 kolom, 3 depth

In [10]:
o = np.ones(((2, 3, 3)))
print(o)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Soal Nomor 5 membuat Matriks 1x3 dengan loop For

In [15]:
for ab in range(5):
    ab = np.array([2, 2, 2])
    print(ab)

[2 2 2]
[2 2 2]
[2 2 2]
[2 2 2]
[2 2 2]


In [16]:
print(ab.shape)

(3,)


In [11]:
for y in range(5):
    y = np.zeros(3)
    print(y)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]


In [18]:
my_array = np.zeros((5,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
for i in my_array:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


In [20]:
print(i.shape)

(3,)
