# Numpy - Multidimensional Data Arrays

## Arange

In [3]:
import numpy as np

In [3]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
#create a range
# arguments: start, stop

x = np.arange(10, 20)

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
#create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step
x

array([10, 12, 14, 16, 18])

In [11]:
x = np.arange(-1, 1, 0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

## Linspace

In [24]:
# membuat interval 0 - 10 dengan 20 sampel
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [7]:
# Angka 1 merupakan batas bawah, angka 10 merupakan batas atas, dan angka 4 merupakan pembagi, jadi 1 sampai 10 dibagi menjadi 4 bagian

np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

## Random Data

In [9]:
from numpy import random

In [17]:
random.rand(5,5) # angka random interval [0,1]

array([[0.73953115, 0.17839366, 0.99764712, 0.16032601, 0.868325  ],
       [0.90009819, 0.6072318 , 0.94483432, 0.25537045, 0.8007853 ],
       [0.65423042, 0.63540396, 0.81510303, 0.53428017, 0.67057088],
       [0.49306151, 0.93955624, 0.90524168, 0.78040466, 0.14329341],
       [0.46851045, 0.09221283, 0.26891455, 0.90873303, 0.27868541]])

In [25]:
# Matriks dengan angka random dengan 5 baris 5 kolom
x = random.randn(5,5)
x

array([[-0.8170022 ,  0.65620437,  0.11867893, -0.02392857,  1.41124773],
       [ 1.81469862, -0.62355788,  0.55958872,  0.27082818, -0.106493  ],
       [ 0.04981069, -0.28061397, -0.44977794, -0.69127082,  0.52005775],
       [ 0.00704628, -1.06539242, -0.86902726, -1.19194296,  0.00615684],
       [-2.53462605,  0.76363644, -1.36186436,  0.71529802, -0.2867804 ]])

In [19]:
x.dtype

dtype('float64')

In [20]:
random.randint(10)

2

In [11]:
random.randint(2, 10, size=4)

array([7, 5, 6, 9])

In [27]:
random.randint(2, 10, size=(2,4))

array([[3, 5, 3, 6],
       [5, 6, 4, 7]])

In [12]:
random.randint(1, 10, size=(2,3,5) )

array([[[8, 6, 2, 5, 8],
        [2, 3, 2, 4, 6],
        [9, 6, 1, 5, 4]],

       [[1, 3, 8, 5, 7],
        [3, 7, 9, 4, 3],
        [2, 8, 4, 1, 3]]])

### Soal 1 Generate array 1 dimensi yang memuat 5 random integer interval [0, 100]

In [28]:
random.randint(0, 100, size=5)

array([54, 69, 97, 32, 92])

### Soal 2 Generate array 2 dimensi yang memuat 3 baris, tiap baris memuat 5 random integer dari 0 sampai 100

In [32]:
random.randint(0, 100, size=(3,5))

array([[63, 77, 23, 14, 93],
       [ 3, 28, 94, 10,  9],
       [13, 97, 21, 88, 18]])

### Soal 3 Generate 30 elemen dari 1,5 sampai 5,5

In [38]:
b = np.linspace(1.5, 5.5, 30)
b

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

## Adding, removing, and sorting elements

In [40]:
# Append
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.append(arr, (10,11,12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
arr1 = np.array([[1,2,3],
                [2,4,6]])
arr1

array([[1, 2, 3],
       [2, 4, 6]])

In [17]:
np.append(arr1, [[4,5,6]], axis=0) 
# Maksut dari axis=0 adalah baris jadi kode diatas menambahkan baris

array([[1, 2, 3],
       [2, 4, 6],
       [4, 5, 6]])

In [19]:
a = np.array([[1, 2, 8], [5, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[1 2 8]
 [5 8 9]
 [1 2 3]
 [4 5 6]]


In [22]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6]])
e = np.concatenate((c, d.T), axis=1)
print(e)

[[1 2 5]
 [3 4 6]]


In [23]:
x = np.array([[1,2,3], [1,1,1]])
y = np.array([[3,3,1], [1,2,3]])
x = np.concatenate((x, y), axis = 1)
print(x)

[[1 2 3 3 3 1]
 [1 1 1 1 2 3]]


## Sorting

In [24]:
# Sorting np.sort()

arr3 = np.array([2, 5, 6, 9, 10, 2, 4, 7, 9, 8, 7, 20, 11,])
np.sort(arr3)

array([ 2,  2,  4,  5,  6,  7,  7,  8,  9,  9, 10, 11, 20])

In [26]:
#Concatenate arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Delete elements of Array

In [27]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Shape and size of an array

In [31]:
arr4 = np.array([[[0, 1, 2, 3],
                  [4, 5, 6, 7]],
                 
                  [[0, 1, 2, 3],
                  [4, 5, 6, 7]],
                
                  [[0, 1, 2 ,3],
                  [4, 5, 6, 7]]])
print(arr4)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [32]:
 arr4.ndim

3

In [33]:
arr4.size

24

In [34]:
arr4.shape

(3, 2, 4)

## Reshapping an array

In [35]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [36]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

## Exercise 3

Soal 1. Buat matriks 3x3 dengan jarak nilai 2 sampai 10

In [39]:
x = np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Soal 2. Concatenate matriks di variabel e dan f

In [47]:
e = np.array([[0, 1, 3],
              [5, 7, 9]])
f = np.array([[0, 2, 4],
              [6, 8, 10]])
penggabungan = np.concatenate((e, f), axis=1) # penggabungan kolom
print(penggabungan)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## Mengubah 1D array ke 2D array (menambahkan axis baru ke array) 

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [49]:
# mengubah array 1 dimensi ke vektor dengan memasukkan axis ke dimensi pertama
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [50]:
a2.shape

(1, 6)

In [52]:
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:
a3.shape

(6, 1)

## Penggunaan np.expand_dims

In [59]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [60]:
b = np.expand_dims(a, axis=1)
b

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [61]:
b.shape

(2, 1, 3)

In [62]:
c = np.expand_dims(a, axis=0)
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [63]:
c.shape

(1, 2, 3)

## Indexing and slicing

In [64]:
data = np.array([1, 2, 3, 4, 5])

In [65]:
data[1]

2

In [66]:
data[:4]

array([1, 2, 3, 4])

In [67]:
data[1:]

array([2, 3, 4, 5])

In [68]:
data[-2:]

array([4, 5])

In [69]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
print(a[a<5]) # print semua nilai yang dibawah 5

[1 2 3 4]


In [73]:
five_up = (a >= 5) # memilih angka yang lebih besar dari 5 dalam array
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [74]:
divisible_by_2 = a[a%2==0] # print angka genap dalam indeks
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [76]:
c = a[(a > 3) & (a < 11)] # memilih elemen yang memenuhi dua kondisi dengan operator & atau |
print(c)

[ 4  5  6  7  8  9 10]


In [78]:
# pipe, or, vertical bar: |
five_upper = (a > 5) | (a == 5)
five_upper

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
a[1,1:3]     # cetak angka pada matriks di axis=1 pada indeks ke-1 sampai elemen ke-3

array([6, 7])

In [102]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
             
               [[0, 2, 4],
                [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [84]:
z.shape

(2, 2, 3)

In [85]:
z[0]     # acces row 0 pada matriks

array([[0, 1, 3],
       [5, 7, 9]])

In [90]:
z[0,1]   # acces row 0, columns 1 pada matriks

array([5, 7, 9])

In [108]:
z[1, 1, 1:]   # access row 1, column 1, depth 1-2

array([ 8, 10])

In [109]:
a = np.array([1,3,1,4,5,2,1])
a

array([1, 3, 1, 4, 5, 2, 1])

In [110]:
a[1:4]

array([3, 1, 4])

## Exercise 4

Soal 1 Buat null vector 1 dimensi ukuran 10 dan updaate nilai kelima menjadi 11

In [114]:
soal1 = np.zeros(10)
soal1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
soal1.size

10

In [118]:
soal1[4] = 11
print(soal1)

[ 0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


Soal 2 tulis program Numpy membuat matriks 2x3 dan ubah ke matriks 3x2

In [124]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
array1.shape

(2, 3)

In [128]:
array1.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Soal 3 tulis program Numpy untuk membuat matriks 2dimensi dengan 1 diborder dan 0 di array

In [131]:
s = np.ones((5, 5))
s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Soal 4 akses matriks Z pada rows=3 column=2 depth=2 

In [144]:
Z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [146]:
Z[2,1,1]

2

# Buat array dari data yang ada

## Membuat array baru dari array yang sudah ada

In [147]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

## Menumpuk (stack) 2 array yang ada baik secara vertikal maupun horizontal

In [149]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [150]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [151]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Kita dapat memisah matrik ke dalam matriks yang lebih kecil menggunakan hsplit. 

In [153]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Jika ingin membagi (split) array menjadi tiga array yang bentuknya sama

In [155]:
y = np.hsplit(x, 3)
print(y)

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [157]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [159]:
z = np.hsplit(x, (3, 5))

print(z)

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5],
       [16, 17]]), array([[ 6,  7,  8,  9, 10, 11, 12],
       [18, 19, 20, 21, 22, 23, 24]])]


In [162]:
m = np.hsplit(x, (1,3))

m

[array([[ 1],
        [13]]),
 array([[ 2,  3],
        [14, 15]]),
 array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [16, 17, 18, 19, 20, 21, 22, 23, 24]])]

# Basic Array Operations

In [166]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [167]:
data

array([1, 2])

In [168]:
ones

array([1, 1])

In [169]:
data + ones    #  # matriks yang ada pada variabel data akan ditambahkan dengan variabel ones

array([2, 3])

In [170]:
data - ones

array([0, 1])

In [171]:
data * data

array([1, 4])

In [172]:
data / data

array([1., 1.])

In [173]:
a = np.array([1, 2, 3, 4])

a.sum()

10

## Penjumlahan baris atau kolom

In [174]:
b = np.array([[1, 1],
              [2, 2]])
b.sum(axis=0)

array([3, 3])

In [175]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [176]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [177]:
mse = (1/n) * np.sum(np.square(y_pred - labels))

NameError: name 'n' is not defined

# Cara menyimpan dan memuat objek Numpy

In [182]:
a = np.array([1, 2, 3, 4, 5, 6])

In [183]:
np.save('myfile', a)

In [184]:
# load file

b = np.load('myfile.npy')

In [185]:
b

array([1, 2, 3, 4, 5, 6])

## Menyimpan matriks Numpy ke file lain seperti .txt atau .csv atau lainnya

In [186]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [187]:
np.savetxt('myfile2.csv', csv_arr)

In [188]:
np.loadtxt('myfile2.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Assignment

Soal 1 Buat matriks 4x4 dengan nilai antara 0 sampai 3

In [228]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [229]:
x += np.arange(4)
x

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

Soal 2 Buat matriks 4x4 dan ubah menjadi dua matriks sepanjang axis kedua

In [215]:
az = np.array([[0, 1, 2, 3],
      [4, 5, 6, 7],
      [8, 9, 10, 11],
      [12, 13, 14, 15]])
az

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [232]:
bz = np.vsplit(az, 2)

In [233]:
print(bz)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
